# Generated by Django 5.0.3 on 2024-03-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('desc', models.TextField(max_length=100)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
        ),
    ]
